seed: 0
log_dir: "./log"
notes: "pendulum"
run_name: "PlaNet Control"

data:
  test_ratio: 0.2
  num_episodes: 10000
  action_repeat: 1
  ppo_steps: 100000

env:
  name: pendulum
  horizon: 100
  gravity: 10.0

train:
  backbone:
    num_updates: 2000
    test_interval: 10
    x_dim: 2
    a_dim: 2
    hidden_dim: 128
    rnn_hidden_dim: 64
    rnn_input_dim: 64
    min_var: 1e-2
    chunk_length: 32
    batch_size: 128
    lr: 1e-3
    eps: 1e-8
    weight_decay: 1e-6
    clip_grad_norm: 1.0
    disable_gpu: True
    kl_beta: 1.0
    free_nats: 3.0
  cost:
    num_updates: 2500
    test_interval: 10
    chunk_length: 32
    batch_size: 256
    lr: 3e-3
    eps: 1e-8
    weight_decay: 1e-6
    clip_grad_norm: 1.0
    disable_gpu: True

evaluation:
  num_trials: 10
  planning_horizon: 8
  num_iterations: 10
  num_candidates: 1000
  num_elites: 100